# Generated by Django 3.2.7 on 2022-07-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('kid', 'Kid')], max_length=50, verbose_name='Type'),
        ),
    ]
